{{- if .Values.backup.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "adguard-home.fullname" . }}-backup
  labels:
    {{- include "adguard-home.labels" . | nindent 4 }}
data:
{{- if .Values.backup.aws.enabled }}
  AWS_ACCESS_KEY_ID: {{ .Values.backup.aws.accessKeyId | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY:  {{ .Values.backup.aws.secretKey | b64enc | quote }}
  S3_DESTINATION: {{ .Values.backup.aws.s3.destination | b64enc | quote }}
{{- end }}
{{- end }}
