{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) (or (ne .Values.deploymentType "StatefulSet") (not .Values.persistence.volumeClaimTemplates.enabled)) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "adguard-home.fullname" . }}
spec:
  {{- toYaml .Values.persistence.volumeClaimSpec | nindent 2 }}
{{- end -}}
